source 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/ahi-pod-ios-cocoapods'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.4'


target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    
  # Pods for Runner
  pod 'AHIMultiScan', '~> 23.10.0'
  pod 'AHIBodyScan', '~> 23.10.0'
  pod 'AHIFaceScan', '~> 23.10.0'
  pod 'AHIFingerScan', '~> 23.10.0'
    
  pod 'Flutter'
    
    
  # Xcode 15 issue workaround - https://stackoverflow.com/questions/77136958/flutter-xcode-15-error-xcode-dt-toolchain-dir-cannot-be-used-to-evaluate-libr
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end
    
end
