source 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/ahi-pod-ios-cocoapods'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.4'


target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'AHIMultiScan', '~> 23.8'
  pod 'AHIBodyScan', '~> 23.8'
  pod 'AHIFaceScan', '~> 23.8'
  pod 'AHIFingerScan', '~> 23.8'
  
  pod 'Flutter'
end
