
platform :ios, '13.4'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/ahi-dev/ahi-pod-ios-cocoapods-dev.git'
#source 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/ahi-pod-ios-cocoapods'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'AHIMultiScan', '~> 22.0'
  pod 'AHIBodyScan', '~> 22.0'
  pod 'AHIFaceScan', '~> 22.0'
  pod 'AHIFingerScan', '~> 22.0'
  pod 'Flutter'

end
