require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/ahi-pod-ios-cocoapods'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.4'


install! 'cocoapods', :deterministic_uuids => false

target 'AHIReactNativeMultiScanBoilerPlate' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # required for the MultiScan SDK
  use_frameworks!

  # Pods for ahi_uikit_multiscan_boilerplate
  pod 'AHIMultiScan', '~> 22.0'
  pod 'AHIBodyScan', '~> 22.0'
  pod 'AHIFaceScan', '~> 22.0'
  pod 'AHIFingerScan', '~> 22.0'

  target 'AHIReactNativeMultiScanBoilerPlateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
