source 'https://cdn.cocoapods.org/'
source 'https://github.com/ahi-dev/ahi-pod-ios-cocoapods-dev.git'


platform :ios, '15.4'

target 'ahi_uikit_multiscan_boilerplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ahi_uikit_multiscan_boilerplate
  pod 'AHIMultiScan', '~> 22.0'
  pod 'AHIBodyScan', '~> 22.0'
  pod 'AHIFaceScan', '~> 22.0'
  

end
