source 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/ahi-pod-ios-cocoapods'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.4'


target 'ahi_swiftui_multiscan_boilerplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ahi_swiftui_multiscan_boilerplate
  pod 'AHIMultiScan', '~> 23.8'
  pod 'AHIBodyScan', '~> 23.8'
  pod 'AHIFaceScan', '~> 23.8'
  pod 'AHIFingerScan', '~> 23.8'
end
